--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nicholass003/NicholasLeaderboard
build-by-default: true
branches:
- main
projects:
  NicholasLeaderboard:
    path: ""
    icon: "leaderboard.png"
...
