name: NicholasLeaderboard
api: 5.0.0
version: 0.0.1-tester
main: nicholass003\nicholasleaderboard\NicholasLeaderboard
author: nicholass003
permissions:
  nicholasleaderboard.command:
    description: "Allows to usage NicholasLeaderboard Default Command"
    default: true
  nicholasleaderboard.command.create:
    description: "Allows to usage NicholasLeaderboard Create Command"
    default: op
  nicholasleaderboard.command.delete:
    description: "Allows to usage NicholasLeaderboard Delete Command"
    default: op
  nicholasleaderboard.command.entities:
    description: "Allows to usage NicholasLeaderboard Entities Command"
    default: op
  nicholasleaderboard.command.resetentity:
    description: "Allows to usage NicholasLeaderboard Reset Entity Command"
    default: op
  nicholasleaderboard.command.type:
    description: "Allows to usage NicholasLeaderboard Type Command"
    default: op
